title: "Eisuke Yoshida"
email: "info@eisyos.com"
domain: "eisyos.com"
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://eisyos.com" # the base hostname & protocol for your site, e.g. http://example.com

remote_theme: riggraz/no-style-please
plugins:
  - jekyll-feed

theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: false # show blog description in home page

